config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100" }
	validates :image, presence: true
	validates :description,  presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :pins

         validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
 
  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :destroy]
  before_action :authenticate_user!, except: [:index, :show]


  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)
  end

  # GET /pins/1
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.' 
    else
      render :new 
    end
  end

  # PATCH/PUT /pins/1
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.' 
    else
      render :edit
    end
  end

  # DELETE /pins/1
  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Access Denied" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to root_path do %> <span class="glyphicon glyphicon-home"></span>Home<% end %></li>
        <li><%= link_to about_path do %> <span class=""></span>About<% end %></li>
        <% if user_signed_in? %>
          <li><%= link_to new_pin_path do %> <span class="glyphicon glyphicon-plus"></span>New Pin<% end %></li>
          <li><%= link_to edit_user_registration_path do %><span class="glyphicon glyphicon-wrench"></span>Account Settings<% end %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
     
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<!-- <%= content_tag(:div, msg, class: "alert alert-info") %> -->
			<div class="alert alert-info fade in" id="flash-<%= name %>">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<%= msg %>
			</div>
			
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Pinteresting</h1>
	<h3>The world's premier Pinterest lookalike</h3>
		<p>
			<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
			<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
</div>

app/views/pages/about.html.erb
<div class="panel panel-default">
	<div class="panel-heading"><h1 class="panel-title">About</h1></div>
	<div class="panel-body">
		<p> This site was designed as a part of the One Month Rails course at <a href="www.onemonth.com">OneMonth.com</a> It is not actually intended to be innovative or original in any particular way, but as an exercise of techniques and practices in web app development. </p>
		<p> The Author is Donny Mason, a recently graduated student of Networking and Programming, as he attempts to pad his resume a bit by learning more skills. </p>
	</div>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>
<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>
<div id="pins" class="transitions-enabled">
  <div class="row">
    <% @pins.each do |pin| %>

      <div class="col-md-8">
        <div class="box panel panel-default center">
          <%= link_to pin_path(pin) do %>
          <%= image_tag pin.image.url(:original) %>
          <% end %>
            <div class="panel-body">
              <h3 class="panel-title"><%= pin.description %><br />
              <small><%= pin.user.name if pin.user %></small></h3>
            </div>
            <% if pin.user == current_user %>
            <div class="panel-footer small">
              <table width="100%">
                <tr>
                  <td class="text-left">
                     <%= link_to edit_pin_path(pin) do %>
                      <span class="glyphicon glyphicon-wrench"></span>Edit
                    <% end %>
                  </td>
                  <td class="text-right">
                    <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      Destroy <span class="glyphicon glyphicon-trash"></span>
                      <% end %> 
                  </td>           
                </tr>
              </table>
            </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
</div>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>
<div class="row">
	<div class="col-md-8 col-md-offset-4">
		<div class="box panel panel-default center">
		<%= image_tag @pin.image.url(:original) %>
			<div class="panel-body">
		        <h3 class="panel-title"><%= @pin.description %><br />
		        <small><%= @pin.user.name if @pin.user %></small></h3>
		    </div>
			<% if @pin.user == current_user %>
				<div class="panel-footer small">
			        <table width="100%">
			        <tr>
			            <td class="text-left">
			              <%= link_to edit_pin_path(@pin) do %>
			              	<span class="glyphicon glyphicon-wrench"></span>Edit
			              <% end %>
			            </td>
			            <td class="text-right">
			               <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      Destroy <span class="glyphicon glyphicon-trash"></span>
                      <% end %>
			            </td>		        
			          </tr>
			        </table>
			    </div>
			<% end %>
		</div>
	</div>
</div>